#!/bin/bash

bbl="*.bbl"
toc="*.toc"
aux="*.aux"
log="*.log"
blg="*.blg"
syn="*.synctex.gz*"
lot="*.lot"
lof="*.lof"

echo
echo "cleaning '${PWD}' for github commit and push..."
echo
echo "********************************************************************************"
echo -e "  removing '$bbl' '$toc' '$aux' '$log' '$blg' '$syn' '$lot' '$lof'"
echo "********************************************************************************"
echo
counterfound=0
counterremoved=0
for f in $(find . -name "$aux" -or -name "$bbl"\
	-or -name "$toc" -or -name "$log" -or -name "$blg" -or -name\
	"$syn" -or -name "$lot" -or -name "$lof" )
do  
	counterfound=$((counterfound+1))
	echo -e "#### --->\t found $f "
done
echo
echo "********************************************************************************"
echo -e "\t $counterfound files found..."
echo "********************************************************************************"
echo

for f in $(find . -name "$aux" -or -name "$bbl"\
	-or -name "$toc" -or -name "$log" -or -name "$blg" -or -name\
	"$syn" -or -name "$lot" -or -name "$lof" )
do 
	counterremoved=$((counterremoved+1))
	echo -e "xxxx <---\t removing $f "
	rm $f
done

echo
echo -e "\t $counterremoved files removed..."
echo
echo "'${PWD}' is now veryclean"
echo "********************************************************************************"



